### ISSUE TITLE
Girjournal hanging at startup

### ISSUE THREAD

**Issue by papog** [GitJournal/GitJournal#591]
On my Android phone (Pixel 4, up to date with Android 12), Girjournal now stays stuck showing the Girjournal icon whenever I start it.

**Comment by timharton** [comment]
I have the same issue on my OnePlus 7

**Comment by ellcs** [comment]
I have the same issue with an fairphone 3 on Android 10. I guess it is not hardware related. I recently bought the pro version after the `ssh-key` fix. It's the second time now, that the app is not usable for me. :(

The GitJournal version is `1.83.0` (provided by the android preferences).

Here is the logcat output:

```
130|FP3:/mnt/sdcard/Download $ grep -i "gitjo" logcat.txt
01-20 09:52:21.269  1397  2558 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.gitjournal.gitjournal/.MainActivity bnds=[23,1376][230,1662] (has extras)} from uid 10125
01-20 09:52:21.352  1397  1563 I ActivityManager: Start proc 9414:io.gitjournal.gitjournal/u0a252 for activity {io.gitjournal.gitjournal/io.gitjournal.gitjournal.MainActivity}
01-20 09:59:33.130  1397  2560 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.gitjournal.gitjournal/.MainActivity bnds=[649,1980][866,2119] (has extras)} from uid 10125
01-20 10:01:44.922  1397  1554 I ActivityManager: Killing 9414:io.gitjournal.gitjournal/u0a252 (adj 905): remove task
01-20 10:01:45.011  1397  3370 I WindowManager: WIN DEATH: Window{8f82051 u0 io.gitjournal.gitjournal/io.gitjournal.gitjournal.MainActivity}
01-20 10:01:47.298  1397  2559 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.gitjournal.gitjournal/.MainActivity bnds=[649,1980][866,2119] (has extras)} from uid 10125
01-20 10:01:47.335  1397  1563 I ActivityManager: Start proc 10745:io.gitjournal.gitjournal/u0a252 for activity {io.gitjournal.gitjournal/io.gitjournal.gitjournal.MainActivity}
01-20 10:01:47.343 10745 10745 E rnal.gitjourna: Not starting debugger since process cannot load the jdwp agent.
01-20 10:01:47.375 10745 10745 W rnal.gitjourna: JIT profile information will not be recorded: profile file does not exits.
01-20 10:01:47.375 10745 10745 I chatty  : uid=10252(io.gitjournal.gitjournal) identical 3 lines
01-20 10:01:47.375 10745 10745 W rnal.gitjourna: JIT profile information will not be recorded: profile file does not exits.
01-20 10:01:47.431 10745 10745 W rnal.gitjournal: type=1400 audit(0.0:821): avc: denied { read } for name="max_map_count" dev="proc" ino=88061 scontext=u:r:untrusted_app:s0:c252,c256,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0
01-20 10:01:47.506 10745 10745 W rnal.gitjourna: Accessing hidden method Landroid/view/WindowInsets;->getInsets(I)Landroid/graphics/Insets; (blacklist, linking, denied)
01-20 10:01:47.506 10745 10745 W rnal.gitjourna: Accessing hidden method Landroid/view/WindowInsets;->getInsets(I)Landroid/graphics/Insets; (blacklist, linking, denied)
01-20 10:01:47.509 10745 10745 W rnal.gitjourna: Accessing hidden method Landroid/view/WindowInsets$Type;->ime()I (blacklist, linking, denied)
01-20 10:01:47.509 10745 10745 W rnal.gitjourna: Accessing hidden method Landroid/view/WindowInsets$Type;->ime()I (blacklist, linking, denied)
01-20 10:01:47.604 10745 10770 E flutter : #1      Date.getDateTime (package:gitjournal/settings/app_config.dart:187)
01-20 10:01:47.604 10745 10770 E flutter : #2      AppConfig.load (package:gitjournal/settings/app_config.dart:62)
01-20 10:01:47.604 10745 10770 E flutter : #3      main (package:gitjournal/main.dart:30)
01-20 10:03:53.412  1397  1781 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.gitjournal.gitjournal/.MainActivity bnds=[649,1980][866,2119] (has extras)} from uid 10125
```

**Comment by lucidBrot** [comment]
I'm on lineageos 17, same issue since I updated today. To narrow the issue introduction down: Last time i updated I got the experimental history view - so this bug must have been introduced after that was added.  

(I had the history view enabled, but disabled it again in hopes of getting rid of slow startup times that I started having then. That is probably unrelated though)

I can not submit a bug report from the app, since it never finishes starting, but I can also provide the logcat from my windows computer, obtained using  
```
adb logcat | findstr gitjournal
```

Before the start of this excerpt I Force Stopped gitjournal:  
```logcat
01-20 21:06:13.813 21994 21994 D AppButtonsPrefCtl: Stopping package io.gitjournal.gitjournal
01-20 21:06:13.813  4250 13709 I ActivityManager: Force stopping io.gitjournal.gitjournal appid=10295 user=0: from pid 21994
01-20 21:06:13.820 21994 21994 D AppButtonsPrefCtl: Sending broadcast to query restart status for io.gitjournal.gitjournal
01-20 21:06:13.897 21994 21994 D AppButtonsPrefCtl: Sending broadcast to query restart status for io.gitjournal.gitjournal
01-20 21:06:13.901 21994 21994 D AppButtonsPrefCtl: Sending broadcast to query restart status for io.gitjournal.gitjournal
01-20 21:06:13.964 21994 21994 D AppButtonsPrefCtl: Sending broadcast to query restart status for io.gitjournal.gitjournal
01-20 21:06:13.967 21994 21994 D AppButtonsPrefCtl: Got broadcast response: Restart status for io.gitjournal.gitjournal false
01-20 21:06:14.001 21994 21994 D AppButtonsPrefCtl: Got broadcast response: Restart status for io.gitjournal.gitjournal false
01-20 21:06:21.933  4250  5589 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=io.gitjournal.gitjournal cmp=io.gitjournal.gitjournal/.MainActivity} from uid 1000
01-20 21:06:21.998  4250  4290 I ActivityManager: Start proc 22345:io.gitjournal.gitjournal/u0a295 for pre-top-activity {io.gitjournal.gitjournal/io.gitjournal.gitjournal.MainActivity}
01-20 21:06:22.115 22345 22345 I chatty  : uid=10295(io.gitjournal.gitjournal) identical 5 lines
01-20 21:06:22.175 22345 22345 W rnal.gitjournal: type=1400 audit(0.0:43685): avc: denied { read } for name="max_map_count" dev="proc" ino=120705513 scontext=u:r:untrusted_app:s0:c39,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=io.gitjournal.gitjournal
01-20 21:06:22.265 22345 22345 I chatty  : uid=10295(io.gitjournal.gitjournal) identical 1 line
01-20 21:06:22.389 22345 22370 E flutter : #1      Date.getDateTime (package:gitjournal/settings/app_config.dart:187)
01-20 21:06:22.389 22345 22370 E flutter : #2      AppConfig.load (package:gitjournal/settings/app_config.dart:62)
01-20 21:06:22.389 22345 22370 E flutter : #3      main (package:gitjournal/main.dart:30)
```

And a second time, to make sure it's without unreproducible stuff:  
```logcat
01-20 21:12:17.558 21994 21994 D AppButtonsPrefCtl: Sending broadcast to query restart status for io.gitjournal.gitjournal
01-20 21:12:17.727 21994 21994 D AppButtonsPrefCtl: Got broadcast response: Restart status for io.gitjournal.gitjournal true
01-20 21:12:17.752 21994 21994 V BatteryUtils: package: io.gitjournal.gitjournal
01-20 21:12:23.351 21994 21994 D AppButtonsPrefCtl: Stopping package io.gitjournal.gitjournal
01-20 21:12:23.352  4250 12176 I ActivityManager: Force stopping io.gitjournal.gitjournal appid=10295 user=0: from pid 21994
01-20 21:12:23.353  4250 12176 I ActivityManager: Killing 22345:io.gitjournal.gitjournal/u0a295 (adj 900): stop io.gitjournal.gitjournal
01-20 21:12:23.354  4250 12176 W ActivityTaskManager: Force removing ActivityRecord{4a5c750 u0 io.gitjournal.gitjournal/.MainActivity t12397 f}: app died, no saved state
01-20 21:12:23.369 21994 21994 D AppButtonsPrefCtl: Sending broadcast to query restart status for io.gitjournal.gitjournal
01-20 21:12:23.440 21994 21994 D AppButtonsPrefCtl: Sending broadcast to query restart status for io.gitjournal.gitjournal
01-20 21:12:23.443 21994 21994 D AppButtonsPrefCtl: Sending broadcast to query restart status for io.gitjournal.gitjournal
01-20 21:12:23.502 21994 21994 D AppButtonsPrefCtl: Sending broadcast to query restart status for io.gitjournal.gitjournal
01-20 21:12:23.503 21994 21994 D AppButtonsPrefCtl: Got broadcast response: Restart status for io.gitjournal.gitjournal false
01-20 21:12:23.531 21994 21994 D AppButtonsPrefCtl: Got broadcast response: Restart status for io.gitjournal.gitjournal false
01-20 21:12:29.548  4250  5588 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=io.gitjournal.gitjournal cmp=io.gitjournal.gitjournal/.MainActivity} from uid 1000
01-20 21:12:29.614  4250  4290 I ActivityManager: Start proc 22946:io.gitjournal.gitjournal/u0a295 for pre-top-activity {io.gitjournal.gitjournal/io.gitjournal.gitjournal.MainActivity}
01-20 21:12:29.643 22946 22946 I chatty  : uid=10295(io.gitjournal.gitjournal) identical 5 lines
01-20 21:12:29.665 22946 22946 W rnal.gitjournal: type=1400 audit(0.0:43686): avc: denied { read } for name="max_map_count" dev="proc" ino=120705513 scontext=u:r:untrusted_app:s0:c39,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=io.gitjournal.gitjournal
01-20 21:12:29.715 22946 22946 I chatty  : uid=10295(io.gitjournal.gitjournal) identical 1 line
01-20 21:12:29.768 22946 22971 E flutter : #1      Date.getDateTime (package:gitjournal/settings/app_config.dart:187)
01-20 21:12:29.768 22946 22971 E flutter : #2      AppConfig.load (package:gitjournal/settings/app_config.dart:62)
01-20 21:12:29.768 22946 22971 E flutter : #3      main (package:gitjournal/main.dart:30)
```

### System Info
Gitjournal Version `1.83.0`   
Installed from Google Play Store  
Android version 10
OS Build Number: `lineage_beryllium-userdebug 10 QQ3A.200805.001 c65720e3ac`  

### Remarks  
* I have not attempted to reboot my phone because my phone has some known issues with rebooting.   
* I have not attempted to wipe the cache of gitjournal because I don't want to accidentally make things worse.  
* I am not using a git remote.  
* The git history is pretty short - not many commits in there.

**Comment by vHanda** [comment]
@lucidBrot : Thank you. The logs helped a lot.

I'm in the process of writing some more automated tests, as I'd like to write tests for each bug I fix, there have been ways too many regressions lately. Once I'm done with that I'll release version `1.83.2` which will contain this fix.
