### ISSUE TITLE
Startup and Saving slow

### ISSUE THREAD

**Issue by lucidBrot** [GitJournal/GitJournal#595]
On android, apps are sometimes fully stopped and sometimes just in a suspended background state that is restored when reopening the app. In the latter case, no issues. In the former, i.e. when the app was killed (manually or by the system) the startup splash screen is shown for around half a minute.

### User Story  
As a user, I would like to open the app to quickly take a note, save it, and be done with it quickly. For example I might paste something into a note. This should be quick to do.

### Problems
* The startup time of around half a minute (estimated without any actual time measurements) is too long and interrupts my train of thought.  
* Saving the note does not instantly save and close it. Instead, nothing seems to happen. After pressing the save button three times, it did save in one of those problematic scenarios, so I'd say it should be at least three times faster.

I believe that when I first installed the app, these speed issues were not yet present.

### Logs
As copied from the `Settings > Debug`.
<details>
<summary>Three Log Snippets. Click here to expand.</summary>  

#### Fresh Start
I opened the app, it loaded for a long time on the splash screen. Then, before doing anything else, I navigated to the settings to copy this log.  
```log
 {"t":1643286033520,"l":"i","msg":"--------------------------------"}
{"t":1643286033520,"l":"i","msg":"--------------------------------"}
{"t":1643286033520,"l":"i","msg":"--------------------------------"}
{"t":1643286033520,"l":"i","msg":"--------- App Launched ---------"}
{"t":1643286033520,"l":"i","msg":"--------------------------------"}
{"t":1643286033520,"l":"i","msg":"--------------------------------"}
{"t":1643286033520,"l":"i","msg":"--------------------------------"}
{"t":1643286033520,"l":"i","msg":"AppConfig","p":{"onBoardingCompleted":"true","collectCrashReports":"true","version":"0","validateProMode":"true","proExpirationDate":"2022-08-26 19:12:22.000","debugLogLevel":"v","experimentalMarkdownToolbar":"true","experimentalGraphView":"false","experimentalAccounts":"false","experimentalGitMerge":"false","experimentalGitOps":"false","experimentalTagAutoCompletion":"false","experimentalHistory":"false"}}
{"t":1643286033583,"l":"d","msg":"Analytics Collection: true"}
{"t":1643286033583,"l":"d","msg":"Analytics Storage: /data/user/0/io.gitjournal.gitjournal/files/analytics"}
{"t":1643286033601,"l":"i","msg":"Repo Ids [0]"}
{"t":1643286033601,"l":"i","msg":"Current Id 0"}
{"t":1643286033603,"l":"d","msg":"Event.StorageConfig","p":{"folderName":"default","storeInternally":"false","storageLocation":"/storage/6F63-1277/Android/media/io.gitjournal.gitjournal/Notes/priv-notes/GitJournal","id":"0"}}
{"t":1643286033603,"l":"d","msg":"Event.FolderConfig","p":{"noteFileNameFormat":"FromTitle","journalNoteFileNameFormat":"FromTitle","yamlModifiedKey":"modified","yamlCreatedKey":"created","yamlTagsKey":"tags","yamlHeaderEnabled":"false","defaultEditor":"Markdown","defaultView":"Standard","defaultFileFormat":"Markdown","sortingField":"Modified","sortingOrder":"desc","showNoteSummary":"true","folderViewHeaderType":"TitleGenerated","imageLocationSpec":".","titleSettings":"h1","inlineTagPrefixes":"#","emojify":"false","allowedFileExts":".md .txt .org","id":"0"}}
{"t":1643286033603,"l":"d","msg":"Event.GitConfig","p":{"gitAuthor":"true","gitAuthorEmail":"true","sshPublicKey":"false","sshPrivateKey":"false","sshPassword":"false","id":"0"}}
{"t":1643286033603,"l":"d","msg":"Event.Settings","p":{"customMetaData":"","defaultNewNoteFolderSpec":"false","journalEditordefaultNewNoteFolderSpec":"","journalEditorSingleNote":"false","remoteSyncFrequency":"automatic","version":"3","markdownDefaultView":"Last Used","markdownLastUsedView":"Edit","homeScreen":"all_notes","theme":"default","lightTheme":"LightDefault","darkTheme":"DarkDefault","zenMode":"false","swipeToDelete":"false","emojiParser":"true","bottomMenuBar":"true","confirmDelete":"true","id":"0"}}
{"t":1643286033603,"l":"i","msg":"Loading Repo at path /storage/6F63-1277/Android/media/io.gitjournal.gitjournal/Notes/priv-notes/GitJournal/journal/"}
{"t":1643286033605,"l":"i","msg":"App Version: 1.83.2"}
{"t":1643286033605,"l":"i","msg":"App Build Number: 3433"}
{"t":1643286033633,"l":"i","msg":"Sending 118 events"}
{"t":1643286035539,"l":"i","msg":"Sent 118 Analytics Events"}
{"t":1643286035553,"l":"i","msg":"Sending 0 events"}
{"t":1643286035741,"l":"i","msg":"Sent 0 Analytics Events"}
{"t":1643286035751,"l":"i","msg":"Sending 0 events"}
{"t":1643286035932,"l":"i","msg":"Sent 0 Analytics Events"}
{"t":1643286035934,"l":"i","msg":"Sending 0 events"}
{"t":1643286036118,"l":"i","msg":"Sent 0 Analytics Events"}
{"t":1643286063412,"l":"i","msg":"_commitUntracked: 0:00:29.803441"}
{"t":1643286063416,"l":"d","msg":"BlobCTimeBuilder Cache Size: 24.81 Kb"}
{"t":1643286063423,"l":"d","msg":"FileMTimeBuilder Cache Size: 21.05 Kb"}
{"t":1643286063427,"l":"d","msg":"Loading MTimeCache: 171 items"}
{"t":1643286063427,"l":"d","msg":"Loading CTimeCache: 288 items"}
{"t":1643286063428,"l":"i","msg":"Branch master"}
{"t":1643286063428,"l":"i","msg":"Cache Directory: /data/user/0/io.gitjournal.gitjournal/files/0"}
{"t":1643286063429,"l":"i","msg":"Checking if ProMode should be enabled. Exp: 2022-08-26 19:12:22.000"}
{"t":1643286063429,"l":"i","msg":"Not checking PurchaseInfo as exp = 2022-08-26 19:12:22.000"}
{"t":1643286063479,"l":"d","msg":"Received MediaFile Share with App (media): []"}
{"t":1643286063526,"l":"i","msg":"Notes Cache Loaded: 20 items"}
{"t":1643286063529,"l":"i","msg":"Finished loading the notes cache - 0:00:00.100917"}
{"t":1643286063536,"l":"i","msg":"Built Git Time Cache - 0:00:00.006948"}
{"t":1643286063656,"l":"i","msg":"Loading View 0_summary_v2: 0:00:00.017807"}
{"t":1643286066721,"l":"i","msg":"Finished loading all the notes - 0:00:03.191317"}
{"t":1643286066726,"l":"i","msg":"_commitUntracked: 0:00:03.296412"}
{"t":1643286066726,"l":"d","msg":"Not syncing because RemoteRepo not configured"}
{"t":1643286078687,"l":"d","msg":"Event.DrawerSettings"}
```

#### After Saving Note  
The app was not killed before this. It came back quickly to the saved state.  
I opened a note, pasted one line, then hit the save button. Since nothing happened, I hit it again. And again. Then the note finally closed and I navigated to the debug settings to copy this log:  
```log
{"t":1643286033520,"l":"i","msg":"--------------------------------"}
{"t":1643286033520,"l":"i","msg":"--------------------------------"}
{"t":1643286033520,"l":"i","msg":"--------------------------------"}
{"t":1643286033520,"l":"i","msg":"--------- App Launched ---------"}
{"t":1643286033520,"l":"i","msg":"--------------------------------"}
{"t":1643286033520,"l":"i","msg":"--------------------------------"}
{"t":1643286033520,"l":"i","msg":"--------------------------------"}
{"t":1643286033520,"l":"i","msg":"AppConfig","p":{"onBoardingCompleted":"true","collectCrashReports":"true","version":"0","validateProMode":"true","proExpirationDate":"2022-08-26 19:12:22.000","debugLogLevel":"v","experimentalMarkdownToolbar":"true","experimentalGraphView":"false","experimentalAccounts":"false","experimentalGitMerge":"false","experimentalGitOps":"false","experimentalTagAutoCompletion":"false","experimentalHistory":"false"}}
{"t":1643286033583,"l":"d","msg":"Analytics Collection: true"}
{"t":1643286033583,"l":"d","msg":"Analytics Storage: /data/user/0/io.gitjournal.gitjournal/files/analytics"}
{"t":1643286033601,"l":"i","msg":"Repo Ids [0]"}
{"t":1643286033601,"l":"i","msg":"Current Id 0"}
{"t":1643286033603,"l":"d","msg":"Event.StorageConfig","p":{"folderName":"default","storeInternally":"false","storageLocation":"/storage/6F63-1277/Android/media/io.gitjournal.gitjournal/Notes/priv-notes/GitJournal","id":"0"}}
{"t":1643286033603,"l":"d","msg":"Event.FolderConfig","p":{"noteFileNameFormat":"FromTitle","journalNoteFileNameFormat":"FromTitle","yamlModifiedKey":"modified","yamlCreatedKey":"created","yamlTagsKey":"tags","yamlHeaderEnabled":"false","defaultEditor":"Markdown","defaultView":"Standard","defaultFileFormat":"Markdown","sortingField":"Modified","sortingOrder":"desc","showNoteSummary":"true","folderViewHeaderType":"TitleGenerated","imageLocationSpec":".","titleSettings":"h1","inlineTagPrefixes":"#","emojify":"false","allowedFileExts":".md .txt .org","id":"0"}}
{"t":1643286033603,"l":"d","msg":"Event.GitConfig","p":{"gitAuthor":"true","gitAuthorEmail":"true","sshPublicKey":"false","sshPrivateKey":"false","sshPassword":"false","id":"0"}}
{"t":1643286033603,"l":"d","msg":"Event.Settings","p":{"customMetaData":"","defaultNewNoteFolderSpec":"false","journalEditordefaultNewNoteFolderSpec":"","journalEditorSingleNote":"false","remoteSyncFrequency":"automatic","version":"3","markdownDefaultView":"Last Used","markdownLastUsedView":"Edit","homeScreen":"all_notes","theme":"default","lightTheme":"LightDefault","darkTheme":"DarkDefault","zenMode":"false","swipeToDelete":"false","emojiParser":"true","bottomMenuBar":"true","confirmDelete":"true","id":"0"}}
{"t":1643286033603,"l":"i","msg":"Loading Repo at path /storage/6F63-1277/Android/media/io.gitjournal.gitjournal/Notes/priv-notes/GitJournal/journal/"}
{"t":1643286033605,"l":"i","msg":"App Version: 1.83.2"}
{"t":1643286033605,"l":"i","msg":"App Build Number: 3433"}
{"t":1643286033633,"l":"i","msg":"Sending 118 events"}
{"t":1643286035539,"l":"i","msg":"Sent 118 Analytics Events"}
{"t":1643286035553,"l":"i","msg":"Sending 0 events"}
{"t":1643286035741,"l":"i","msg":"Sent 0 Analytics Events"}
{"t":1643286035751,"l":"i","msg":"Sending 0 events"}
{"t":1643286035932,"l":"i","msg":"Sent 0 Analytics Events"}
{"t":1643286035934,"l":"i","msg":"Sending 0 events"}
{"t":1643286036118,"l":"i","msg":"Sent 0 Analytics Events"}
{"t":1643286063412,"l":"i","msg":"_commitUntracked: 0:00:29.803441"}
{"t":1643286063416,"l":"d","msg":"BlobCTimeBuilder Cache Size: 24.81 Kb"}
{"t":1643286063423,"l":"d","msg":"FileMTimeBuilder Cache Size: 21.05 Kb"}
{"t":1643286063427,"l":"d","msg":"Loading MTimeCache: 171 items"}
{"t":1643286063427,"l":"d","msg":"Loading CTimeCache: 288 items"}
{"t":1643286063428,"l":"i","msg":"Branch master"}
{"t":1643286063428,"l":"i","msg":"Cache Directory: /data/user/0/io.gitjournal.gitjournal/files/0"}
{"t":1643286063429,"l":"i","msg":"Checking if ProMode should be enabled. Exp: 2022-08-26 19:12:22.000"}
{"t":1643286063429,"l":"i","msg":"Not checking PurchaseInfo as exp = 2022-08-26 19:12:22.000"}
{"t":1643286063479,"l":"d","msg":"Received MediaFile Share with App (media): []"}
{"t":1643286063526,"l":"i","msg":"Notes Cache Loaded: 20 items"}
{"t":1643286063529,"l":"i","msg":"Finished loading the notes cache - 0:00:00.100917"}
{"t":1643286063536,"l":"i","msg":"Built Git Time Cache - 0:00:00.006948"}
{"t":1643286063656,"l":"i","msg":"Loading View 0_summary_v2: 0:00:00.017807"}
{"t":1643286066721,"l":"i","msg":"Finished loading all the notes - 0:00:03.191317"}
{"t":1643286066726,"l":"i","msg":"_commitUntracked: 0:00:03.296412"}
{"t":1643286066726,"l":"d","msg":"Not syncing because RemoteRepo not configured"}
{"t":1643286078687,"l":"d","msg":"Event.DrawerSettings"}
{"t":1643286181172,"l":"d","msg":"Note modified"}
{"t":1643286181174,"l":"d","msg":"Note modified - saving"}
{"t":1643286181176,"l":"d","msg":"Event.NoteUpdated"}
{"t":1643286181803,"l":"d","msg":"Got updateNote lock"}
{"t":1643286184788,"l":"d","msg":"Note modified"}
{"t":1643286184788,"l":"d","msg":"Note modified - saving"}
{"t":1643286184788,"l":"d","msg":"Event.NoteUpdated"}
{"t":1643286192523,"l":"d","msg":"Note modified"}
{"t":1643286192523,"l":"d","msg":"Note modified - saving"}
{"t":1643286192524,"l":"d","msg":"Event.NoteUpdated"}
{"t":1643286193496,"l":"d","msg":"Got updateNote lock"}
{"t":1643286193512,"l":"d","msg":"Note modified"}
{"t":1643286195871,"l":"d","msg":"Event.DrawerSettings"} REDACTED

```
`REDACTED` stands for the last 13882 characters of my note. Containing 235 `\n` characters. This is not the full note. I am surprised this was logged and hope this is not part of the analytics.  

#### Null Check  
A bit later, I noticed a **red Exception** in the log. I didn't do anything on purpose, I think I didn't even navigate away from the debug log - just restored the app from the background as usual (switched to a different app and back).  
The full log is the same as the previous one (same timestamps and everything) but with the following appended:  
```log
{"t":1643286195871,"l":"d","msg":"Event.DrawerSettings"}
{"t":1643286213455,"l":"d","msg":"Got updateNote lock"}
{"t":1643286213461,"l":"e","msg":"Got Exception","ex":"Null check operator used on a null value","stack":[{"uri":"package:flutter/src/widgets/framework.dart","line":1108,"member":"State.setState","isCore":false,"library":"package:flutter/src/widgets/framework.dart","location":"package:flutter/src/widgets/framework.dart 1108","package":"flutter"},{"uri":"package:gitjournal/editors/note_editor.dart","line":486,"member":"NoteEditorState._saveNote","isCore":false,"library":"package:gitjournal/editors/note_editor.dart","location":"package:gitjournal/editors/note_editor.dart 486","package":"gitjournal"},{"uri":"package:gitjournal/editors/note_editor.dart","line":330,"member":"NoteEditorState.exitEditorSelected","isCore":false,"library":"package:gitjournal/editors/note_editor.dart","location":"package:gitjournal/editors/note_editor.dart 330","package":"gitjournal"}]}
{"t":1643286215839,"l":"e","msg":"Got Exception","ex":"Null check operator used on a null value","stack":[{"uri":"package:flutter/src/widgets/framework.dart","line":1108,"member":"State.setState","isCore":false,"library":"package:flutter/src/widgets/framework.dart","location":"package:flutter/src/widgets/framework.dart 1108","package":"flutter"},{"uri":"package:gitjournal/editors/note_editor.dart","line":486,"member":"NoteEditorState._saveNote","isCore":false,"library":"package:gitjournal/editors/note_editor.dart","location":"package:gitjournal/editors/note_editor.dart 486","package":"gitjournal"},{"uri":"package:gitjournal/editors/note_editor.dart","line":330,"member":"NoteEditorState.exitEditorSelected","isCore":false,"library":"package:gitjournal/editors/note_editor.dart","location":"package:gitjournal/editors/note_editor.dart 330","package":"gitjournal"}]}
{"t":1643286240293,"l":"i","msg":"_commitUntracked: 0:00:46.788546"}
{"t":1643286240296,"l":"d","msg":"Not syncing because RemoteRepo not configured"}
{"t":1643286240310,"l":"i","msg":"_commitUntracked: 0:00:26.838110"}
{"t":1643286240310,"l":"d","msg":"Not syncing because RemoteRepo not configured"}
{"t":1643286240325,"l":"i","msg":"_commitUntracked: 0:00:24.481254"}
{"t":1643286240325,"l":"d","msg":"Not syncing because RemoteRepo not configured"}
{"t":1643286240374,"l":"d","msg":"Saving MTimeCache: 171 items"}
{"t":1643286240374,"l":"d","msg":"Saving CTimeCache: 289 items"}
{"t":1643286240441,"l":"d","msg":"Note modified: keep/Loading-quotes.md"}
{"t":1643286827648,"l":"d","msg":"Event.DrawerSettings"}

```

Note that the `Not Syncing` is expected. I'm only reporting this log because of the red glowing `Null check operator used on a null value` exception.  
</details>

### System Info
Pocophone f1, rooted
Lineage OS 17 (Android 10)
Build `lineage_beryllium-userdebug 10 QQ3A.200805.001 c65720e3ac`
GitJournal version `1.83.2` from Google Play Store

I just noticed that there is already another update available. I will report back once I tested in the update version.

**Comment by vHanda** [comment]
When using external storage, GitJournal now does a check for new/modified files on boot and that is what is causing this huge delay.

I definitely need to optimize that code path, and make sure it doesn't block loading the notes.

**Comment by vHanda** [comment]
Would you mind confirming if disabling external storage of the repo fixes both issues for you?

(I'm not sure why saving is blocking, I'll need to investigate)

**Comment by lucidBrot** [comment]
Thanks for the (insanely quick!) reply!

I'm not sure I want to verify this because my setup is a bit intricate (syncthing works with the same directory that gitjournal is using as a repo so that my notes are always up to date on all my devices, on some of which I'm using foambubble) and if something weird happens I might have a lot of effort to fix that. Does disabling the external storage do anything to the filesystem (moving, copying, deleting, ...)?

**Comment by lucidBrot** [comment]
Version `1.83.4`  has reduced the startup time to about five seconds, which is sufferable. Thanks a lot!

It seems saving notes has now stopped working at all though.  

```
02-01 13:45:46.391  4250  5154 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.gitjournal.gitjournal/.MainActivity bnds=[464,641][615,792] (has extras)} from uid 10146
02-01 13:45:46.471  4250  4290 I ActivityManager: Start proc 9866:io.gitjournal.gitjournal/u0a295 for pre-top-activity {io.gitjournal.gitjournal/io.gitjournal.gitjournal.MainActivity}
02-01 13:45:46.503  9866  9866 I chatty  : uid=10295(io.gitjournal.gitjournal) identical 5 lines
02-01 13:45:46.525  9866  9866 W rnal.gitjournal: type=1400 audit(0.0:61520): avc: denied { read } for name="max_map_count" dev="proc" ino=177376205 scontext=u:r:untrusted_app:s0:c39,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=io.gitjournal.gitjournal
02-01 13:45:46.570  9866  9866 I chatty  : uid=10295(io.gitjournal.gitjournal) identical 1 line
02-01 13:45:49.659  2267  2288 I Finsky  : [230487] fqq.a(14): io.gitjournal.gitjournal: Account determined from installer data - [SiCc2nLHFFfRqv6NOJnQs8cbvEq7HagT3j4pEmAxYWQ]
02-01 13:45:49.660  2267  2288 I Finsky  : [230487] fqq.a(63): Billing preferred account via installer for io.gitjournal.gitjournal: [SiCc2nLHFFfRqv6NOJnQs8cbvEq7HagT3j4pEmAxYWQ]
02-01 13:45:49.663  2267  2288 I Finsky  : [230487] fqq.a(14): io.gitjournal.gitjournal: Account determined from installer data - [SiCc2nLHFFfRqv6NOJnQs8cbvEq7HagT3j4pEmAxYWQ]
02-01 13:45:49.664  2267  2288 I Finsky  : [230487] fqq.a(63): Billing preferred account via installer for io.gitjournal.gitjournal: [SiCc2nLHFFfRqv6NOJnQs8cbvEq7HagT3j4pEmAxYWQ]
02-01 13:45:49.664  4250  4288 I ActivityTaskManager: Fully drawn io.gitjournal.gitjournal/.MainActivity: +3s273ms
02-01 13:45:49.695  4250  4288 I ActivityTaskManager: Displayed io.gitjournal.gitjournal/.MainActivity: +3s302ms
02-01 13:46:01.291  9866  9892 E flutter : #1      NoteEditorState._noteModified (package:gitjournal/editors/note_editor.dart:458)
02-01 13:46:01.291  9866  9892 E flutter : #2      NoteEditorState._saveNote (package:gitjournal/editors/note_editor.dart:481)
02-01 13:46:01.291  9866  9892 E flutter : #3      NoteEditorState.exitEditorSelected (package:gitjournal/editors/note_editor.dart:332)
02-01 13:46:01.291  9866  9892 E flutter : #4      EditorAppBar.build.<anonymous closure> (package:gitjournal/editors/common.dart:98)
```

**Comment by lucidBrot** [comment]
I can confirm that the saving works again!  

Both, saving and startup seem to be reasonably fast now.  Almost no delay for saving, and roughly 4-5 seconds startup time. (The first time after updating to `1.83.5` took a bit longer but now it's fine).  

I believe this issue can be closed. Unless you're planning to speed the startup up further.

**Comment by lucidBrot** [comment]
I have to take that back, startup is still sometimes slow. Just less often and less badly. (version `1.83.5`, gplay)

Saving works usually reliably now though, except for the issue that with every save one line is eaten by the app, as tracked at https://github.com/GitJournal/GitJournal/issues/579#issuecomment-1027817290

**Comment by vHanda** [comment]
> I believe this issue can be closed. Unless you're planning to speed the startup and saving up further. It's not yet ideal but it's also no pressing issue imo.

The check for changes on boot and commit is being done using 'dart-git', as I was tired of libgit2. However, dart-git still has to be optimized for this use case, as its ridiculously slow. I'm going to leave this open until I fix this.
