### ISSUE TITLE
Manually provided keys don't always work [generated via OSX]

### ISSUE THREAD

**Issue by tzvetkoff** [GitJournal/GitJournal#85]
Just spotted this:

``` dart
if (!val.startsWith("-----END RSA PRIVATE KEY-----")) {
```
https://github.com/GitJournal/GitJournal/blob/master/lib/setup/key_editors.dart#L35

It actively prevents me from even trying GitJournal.

**Comment by vHanda** [comment]
Eeep. I'll fix it today.

**Comment by vHanda** [comment]
I'm keeping this bug open for now as even with this fix I can no longer clone a private repo - I get a 'Failed Invalid Credentials' while trying to clone. I've been trying to debug this for a while, but I'm knee deep in libgit2 code now, and haven't managed :(

**Comment by vHanda** [comment]
After many hours of debugging it seems that the keys generated via osx's `ssh-keygen` do not seem to work with `libssh2`. I'm not sure why. The one from linux works.

Would you have any idea why?

**Comment by tzvetkoff** [comment]
You mean they don't work at all on clone, or you can't add the key in setup?

**Comment by tzvetkoff** [comment]
P.S. I'll test right away, just to find where I put my old MacBook...

**Comment by vHanda** [comment]
I still haven't made a release with these new changes. I'll let you know
when they are live.

**Comment by tzvetkoff** [comment]
No worries - I can run it in Android emulator

**Comment by vHanda** [comment]
> You mean they don't work at all on clone, or you can't add the key in setup?

I cannot clone. Adding custom keys now works.

**Comment by vHanda** [comment]
You can get the latest apk from the CI - https://circleci.com/gh/GitJournal/GitJournal/272#artifacts/containers/0

You don't need to build it yourself.

**Comment by tzvetkoff** [comment]
Just built it - here's an extract from the logs:

```
I/flutter (10826): 0:01:10.899661	D	GitHostSetupScreenState._startGitClone:	 Cloning git@github.com:tzvetkoff/notes.git
I/GitJournalAndroid(10826): Called method gitClone
I/GitJournalAndroid(10826): .  folderPath: /data/user/0/io.gitjournal.gitjournal.dev/files/journal
I/GitJournalAndroid(10826): .  cloneUrl: git@github.com:tzvetkoff/notes.git
W/io.gitjournal.gitjournal.dev(10826): type=1400 audit(0.0:89): avc: denied { link } for comm=4173796E635461736B202331 name="HEAD.lock" dev="vdc" ino=30699 scontext=u:r:untrusted_app_27:s0:c135,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c135,c256,c512,c768 tclass=file permissive=0 app=io.gitjournal.gitjournal.dev
E/GitJournalLib(10826): Valid: 0
E/GitJournalLib(10826): CertType: 2
E/GitJournalLib(10826): github.com: Invalid certificate
E/GitJournalLib(10826): LibSSH2 Key: 0xc2826ec0
E/GitJournalLib(10826): Url: git@github.com:tzvetkoff/notes.git
W/io.gitjournal.gitjournal.dev(10826): type=1400 audit(0.0:90): avc: denied { link } for comm=4173796E635461736B202331 name="pack_git2_oRidx.lock" dev="vdc" ino=30702 scontext=u:r:untrusted_app_27:s0:c135,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c135,c256,c512,c768 tclass=file permissive=0 app=io.gitjournal.gitjournal.dev
E/GitJournalLib(10826): network   0% (   2 kb,     0/   12)  /  index   0% (    0/   12)
E/GitJournalLib(10826): network   8% (   2 kb,     1/   12)  /  index   8% (    1/   12)
E/GitJournalLib(10826): network  16% (   2 kb,     2/   12)  /  index  16% (    2/   12)
E/GitJournalLib(10826): network  25% (   2 kb,     3/   12)  /  index  25% (    3/   12)
E/GitJournalLib(10826): network  33% (   2 kb,     4/   12)  /  index  33% (    4/   12)
E/GitJournalLib(10826): network  41% (   2 kb,     5/   12)  /  index  41% (    5/   12)
E/GitJournalLib(10826): network  50% (   2 kb,     6/   12)  /  index  50% (    6/   12)
E/GitJournalLib(10826): network  58% (   2 kb,     7/   12)  /  index  58% (    7/   12)
E/GitJournalLib(10826): network  66% (   2 kb,     8/   12)  /  index  66% (    8/   12)
W/io.gitjournal.gitjournal.dev(10826): type=1400 audit(0.0:91): avc: denied { link } for comm=4173796E635461736B202331 name="pack_git2_oRyPXb" dev="vdc" ino=30652 scontext=u:r:untrusted_app_27:s0:c135,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c135,c256,c512,c768 tclass=file permissive=0 app=io.gitjournal.gitjournal.dev
E/GitJournalLib(10826): network  75% (   2 kb,     9/   12)  /  index  66% (    8/   12)
E/GitJournalLib(10826): network  83% (   2 kb,    10/   12)  /  index  75% (    9/   12)
E/GitJournalLib(10826): network  91% (   2 kb,    11/   12)  /  index  83% (   10/   12)
E/GitJournalLib(10826): network 100% (   2 kb,    12/   12)  /  index  91% (   11/   12)
E/GitJournalLib(10826): network 100% (   2 kb,    12/   12)  /  index  91% (   11/   12)
E/GitJournalLib(10826): network 100% (   2 kb,    12/   12)  /  index 100% (   12/   12)
W/io.gitjournal.gitjournal.dev(10826): type=1400 audit(0.0:92): avc: denied { link } for comm=4173796E635461736B202331 name="master.lock" dev="vdc" ino=30708 scontext=u:r:untrusted_app_27:s0:c135,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c135,c256,c512,c768 tclass=file permissive=0 app=io.gitjournal.gitjournal.dev
I/flutter (10826): 0:01:16.299757	D	migrateGitRepo:	 migrateGitRepo journal_local journal
I/flutter (10826): 0:01:16.303885	D	migrateGitRepo:	 toGitRemotePath /data/user/0/io.gitjournal.gitjournal.dev/files/journal
W/io.gitjournal.gitjournal.dev(10826): type=1400 audit(0.0:93): avc: denied { link } for comm=4173796E635461736B202331 name="master.lock" dev="vdc" ino=30732 scontext=u:r:untrusted_app_27:s0:c135,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c135,c256,c512,c768 tclass=file permissive=0 app=io.gitjournal.gitjournal.dev
I/flutter (10826): 0:01:16.315412	D	migrateGitRepo:	 migrateGitRepo: Done
E/flutter (10826): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type '(NotesFolderFS) => void' is not a subtype of type '(NotesFolder) => void'
E/flutter (10826): #0      NotesFolderFS.reset (package:gitjournal/core/notes_folder_fs.dart:50:25)
E/flutter (10826): #1      StateContainer.completeGitHostSetup.<anonymous closure> (package:gitjournal/state_container.dart:225:28)
E/flutter (10826): <asynchronous suspension>
E/flutter (10826): #2      StateContainer.completeGitHostSetup.<anonymous closure> (package:gitjournal/state_container.dart)
E/flutter (10826): #3      StateContainer.completeGitHostSetup (package:gitjournal/state_container.dart:232:6)
E/flutter (10826): #4      GitHostSetupScreenState._startGitClone (package:gitjournal/setup/screens.dart:491:12)
E/flutter (10826): #5      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (10826): #6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (10826): #7      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
E/flutter (10826): #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (10826): #9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (10826): #10     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter (10826): #11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
E/flutter (10826): #12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
E/flutter (10826): #13     GitRepo.clone (package:git_bindings/git_bindings.dart)
E/flutter (10826): #14     _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (10826): #15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (10826): #16     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
E/flutter (10826): #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (10826): #18     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (10826): #19     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter (10826): #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
E/flutter (10826): #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
E/flutter (10826): #22     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
E/flutter (10826): #23     _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (10826): #24     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (10826): #25     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
E/flutter (10826): #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (10826): #27     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (10826): #28     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter (10826): #29     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
E/flutter (10826): #30     _rootRun (dart:async/zone.dart:1126:13)
E/flutter (10826): #31     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (10826): #32     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (10826): #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter (10826): #34     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter (10826): #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter (10826): 
W/io.gitjournal.gitjournal.dev(10826): type=1400 audit(0.0:94): avc: denied { link } for comm=4173796E635461736B202331 name="index.lock" dev="vdc" ino=30819 scontext=u:r:untrusted_app_27:s0:c135,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c135,c256,c512,c768 tclass=file permissive=0 app=io.gitjournal.gitjournal.dev
```

**Comment by tzvetkoff** [comment]
I've fixed it locally by changing https://github.com/GitJournal/GitJournal/blob/master/lib/core/notes_folder_fs.dart#L50 to
``` dart
    var foldersCopy = List<NotesFolderFS>.from(_folders);
```

**Comment by vHanda** [comment]
Yup. I was also just pushing that fix.

Okay. This is great, the cloning worked for you with custom keys. It's the refactor + "All notes view" which I did on Sunday is causing problems.

**Comment by canewsin** [comment]
I'm using git_bindings: dart package, when running example of that package i'm getting the following error. This error happens on Android device.

Error :

```
I/GitJournalAndroid(22859): Called method generateSSHKeys
I/GitJournalAndroid(22859): .  comment: Git Sample App
D/GenerateSSHKeys(22859): Private key already exists. Overwriting
I/GitJournalAndroid(22859): Called method gitClone
I/GitJournalAndroid(22859): .  folderPath: /data/user/0/com.example.git_bindings_example/files/test
I/GitJournalAndroid(22859): .  cloneUrl: git@github.com:canewsin/test.git
W/com.example.git_bindings_example(22859): type=1400 audit(0.0:154103): avc: denied { link } for comm=4173796E635461736B202331 name="HEAD.lock" dev="sda31" ino=2104240 scontext=u:r:untrusted_app_27:s0:c196,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c196,c258,c512,c768 tclass=file permissive=0
E/GitJournalLib(22859): Valid: 0
E/GitJournalLib(22859): CertType: 2
E/GitJournalLib(22859): github.com: Invalid certificate
E/GitJournalLib(22859): LibSSH2 Key: 0x78cff3b3c8
E/GitJournalLib(22859): Url: git@github.com:canewsin/test.git
E/GitJournalLib(22859): GitJournal: Credentials have been tried and they failed
E/GitJournalLib(22859): gj_error_info: -957
E/GitJournalLib(22859): Error -957/-957: Invalid Credentials
I/flutter (22859): GitException: Invalid Credentials
```

**Comment by maxprehl** [comment]
Seeing as this issue is still open I'll comment here (though I've also looked at #351, #353, #576, which all regard key auth)

After some major googling, I have a hunch that the core issue here is about openssh 8.8 being more strict about denying the `ssh-rsa` algorithm (aka `rsa-sha1`)

I hadn't seen many server-side logs from most of the issues on here and other sites, so I dug into the logs on my systems.  For me, the **core server side error** I'm getting is: "key type ssh-rsa not in PubkeyAcceptedAlgorithms"

`journalctl -t sshd -r`

```log
Jun 02 04:55:02 pop-os sshd[2688]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
```

I hope this can help solve the issue for GitJournal and help others hitting the issue right now!

## Research

[This arch wiki thread](https://bbs.archlinux.org/viewtopic.php?id=270005) discusses the issue several months ago when 8.8 hit the arch users.

There's another thread on unix.stackexchange, but the signal to noise ratio is really bad.  [This one guy's response](https://unix.stackexchange.com/a/652838/514808) is a solution for Fedora systems, but I needed one for Ubuntu-based systems.  

## Temporary Workaround

I hit the issue myself on a Pop_OS system (Ubuntu) running 22.04, aka jammy.  I had no issue connecting to and cloning from Ubuntu 20.04 systems, however I was getting denied from the 22.04 system.

The temporary solution I [found](https://bbs.archlinux.org/viewtopic.php?pid=2006291#p2006291) that allows GitJournal to successfully connect is addding the following to `sshd_conf`.

`/etc/ssh/sshd_conf`

```conf
HostKeyAlgorithms +ssh-rsa
PubkeyAcceptedAlgorithms +ssh-rsa
```

**THE REASON THIS SOLUTION IS TEMPORARY:** this re-enables `rsa-sha1`, which is considered a "broken" algo.  It IS a security risk!

## GitJournal Specific Issues

What leads me to posting this issue here and not elsewhere is that GitJournal's ssh connection seems to be the only one that causes the server to get confused about the algorithm.

Regular commandline ssh clients **using the same keypair as GitJournal** would NOT get denied.

I'm not sure how the whole key-exchange stuff works but I'll include both logs using the SAME client public/private keypair.  Hopefully someone here can look into these and figure out how one is negotiating properly and the other is breaking.  Full logs in the gists but I've highlighted the moment of the difference, it happens around Line 128 of both logs. 

Don't mind my public keys btw 😂

### Current GitJournal Failure - sshd log

https://gist.github.com/maxprehl/a5fb8f3c0c5c3d8042fce4d9c3d0a0bc

```log
Jun 02 05:29:22 pop-os sshd[2746]: debug1: userauth-request for user max service ssh-connection method publickey [preauth]
Jun 02 05:29:22 pop-os sshd[2746]: debug1: attempt 1 failures 0 [preauth]
Jun 02 05:29:22 pop-os sshd[2746]: debug2: input_userauth_request: try method publickey [preauth]
Jun 02 05:29:22 pop-os sshd[2746]: debug2: userauth_pubkey: valid user max querying public key ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDdIJYZ1CYpyJVc748kj26/vSENP+zPUQ9OIpzZqbFF4oAUzwBdaW7yoObjxiZZSzLZCoa5du/7tmWIG1jh7bYQEhL3Oe/EDnM47GIDmehXoznGS+XoDOhAthMzu8emSZCGBlFsoUy2eVT7GdHgHt6ayOUE2DCLdASBgEpY3VNq4ZHhxWUmuGmJ+cDJrJdG7V6cpbZDGsacFf7YUnT5ODFO1y47ZCypP0UvG8PHPKWXJANzKdJSAYrZy8OfjgvhLE4AtQ3BS1FaWQ8aIdCIl1E8aaC/ZBrY6Gg55vTImed5p+k1TXESHyRqQzg9iIrzjvfVBEhFIHodRaq71aHJ9nvplK7QlNjkHh0RBxvroi86DVRLRvQyrpXVBzTtl1qzmpshd9+EG0syMsGIRMRa
Jun 02 05:29:22 pop-os sshd[2746]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Jun 02 05:29:22 pop-os sshd[2746]: debug2: userauth_pubkey: authenticated 0 pkalg ssh-rsa [preauth]
```

### Commandline SSH Success - sshd log

https://gist.github.com/maxprehl/c880d6dfc5a0a0a64bf8ed55125825b3

```log
Jun 02 05:35:04 pop-os sshd[2758]: debug1: userauth-request for user max service ssh-connection method publickey [preauth]
Jun 02 05:35:04 pop-os sshd[2758]: debug1: attempt 1 failures 0 [preauth]
Jun 02 05:35:04 pop-os sshd[2758]: debug2: input_userauth_request: try method publickey [preauth]
Jun 02 05:35:04 pop-os sshd[2758]: debug2: userauth_pubkey: valid user max querying public key rsa-sha2-512 AAAAB3NzaC1yc2EAAAADAQABAAABgQDdIJYZ1CYpyJVc748kj26/vSENP+zPUQ9OIpzZqbFF4oAUzwBdaW7yoObjxiZZSzLZCoa5du/7tmWIG1jh7bYQEhL3Oe/EDnM47GIDmehXoznGS+XoDOhAthMzu8emSZCGBlFsoUy2eVT7GdHgHt6ayOUE2DCLdASBgEpY3VNq4ZHhxWUmuGmJ+cDJrJdG7V6cpbZDGsacFf7YUnT5ODFO1y47ZCypP0UvG8PHPKWXJANzKdJSAYrZy8OfjgvhLE4AtQ3BS1FaWQ8aIdCIl1E8aaC/ZBrY6Gg55vTImed5p+k1TXESHyRqQzg9iIrzjvfVBEhFIHodRaq71aHJ9nvplK7QlNjkHh0RBxvroi86DVRLRvQyrpXVBzTtl1qzmpshd9+EG0syMsG
Jun 02 05:35:04 pop-os sshd[2758]: debug1: userauth_pubkey: publickey test pkalg rsa-sha2-512 pkblob RSA SHA256:ZMk85h1AhKou/myuNFFLJuMq6kvVWyuzkpR24WKkB+c [preauth]
Jun 02 05:35:04 pop-os sshd[2758]: debug3: mm_key_allowed: entering [preauth]
```

**Comment by vHanda** [comment]
Closing this in favor of https://github.com/GitJournal/GitJournal/issues/623

I understand the problem far better now.
