### ISSUE TITLE
Failed to clone Exception: Failed to fetch

### ISSUE THREAD

**Issue by TieWay59** [GitJournal/GitJournal#977]
## result 

![image](https://github.com/user-attachments/assets/951c7506-35b8-45f6-a703-8ada722cf98f)

```log
flutter: E GitHostSetupScreenState._startGitClone: Failed to clone Exception: Failed to fetch -  - exitCode: 128package:gitjournal/utils/git_desktop.dart 96:5  _gitCommandViaExecutable
package:gitjournal/setup/clone.dart 68:12       cloneRemotePluggable
package:git_setup/screens.dart 568:7            GitHostSetupScreenState._startGitClone

flutter: D logEvent: Event.GitHostSetupGitCloneError
```

## reprod

env:

```shell
GitJournal on  master [!] is 📦 v1.89.0+10 via 🎯 v3.5.0 
❯ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

GitJournal on  master [!] is 📦 v1.89.0+10 via 🎯 v3.5.0 
❯ uname -a
Linux YTZLDT1810014 6.5.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 16:40:02 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
build command from BUILD.md
```shell
GitJournal on  master [!] is 📦 v1.89.0+10 via 🎯 v3.5.0 
❯ flutter run --flavor dev --debug
```

and then add my repo with SSH key.

full log:

```log
GitJournal on  master [!] is 📦 v1.89.0+10 via 🎯 v3.5.0 
❯ flutter run --flavor dev --debug
Connected devices:
Linux (desktop) • linux  • linux-x64      • Ubuntu
22.04.4 LTS 6.5.0-45-generic
Chrome (web)    • chrome • web-javascript • Google Chrome
127.0.6533.119
[1]: Linux (linux)
[2]: Chrome (chrome)
Please choose one (or "q" to quit): l
Please choose one (or "q" to quit): 1
--flavor is only supported for Android, macOS, and iOS
devices. Flavor-related features may not function
properly and could behave differently in a future
release.
"de": 4 untranslated message(s).
"es": 4 untranslated message(s).
"fa": 4 untranslated message(s).
"fi": 4 untranslated message(s).
"fr": 4 untranslated message(s).
"hi": 4 untranslated message(s).
"hu": 4 untranslated message(s).
"id": 4 untranslated message(s).
"it": 4 untranslated message(s).
"ja": 4 untranslated message(s).
"ko": 4 untranslated message(s).
"pl": 4 untranslated message(s).
"pt": 4 untranslated message(s).
"pt_BR": 4 untranslated message(s).
"ru": 4 untranslated message(s).
"sv": 4 untranslated message(s).
"ta": 4 untranslated message(s).
"vi": 4 untranslated message(s).
"zh": 4 untranslated message(s).
"zh_Hans": 4 untranslated message(s).
"zh_TW": 4 untranslated message(s).
To see a detailed report, use the
untranslated-messages-file
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection> 


This will generate a JSON format file containing all
messages that
need to be translated.
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
✓ Built build/linux/x64/debug/bundle/gitjournal

(gitjournal:1037425): Atk-CRITICAL **: 20:30:09.859: atk_socket_embed: assertion 'plug_id != NULL' failed
Syncing files to device Linux...                         
flutter: I JournalApp.main: --------------------------------
Syncing files to device Linux...                         
flutter: I JournalApp.main: --------------------------------
Syncing files to device Linux...                         
flutter: I JournalApp.main: --------------------------------
Syncing files to device Linux...                         
flutter: I JournalApp.main: --------- App Launched ---------
Syncing files to device Linux...                         
flutter: I JournalApp.main: --------------------------------
Syncing files to device Linux...                         
flutter: I JournalApp.main: --------------------------------
Syncing files to device Linux...                         
flutter: I JournalApp.main: --------------------------------
Syncing files to device Linux...                         
flutter: I JournalApp.main: AppConfig {onBoardingCompleted: false, collectCrashReports: true, version: 0, validateProMode: true, proMode: false, debugLogLevel: v, experimentalMarkdownToolbar: false, experimentalAccounts: false, experimentalTagAutoCompletion: false}
Syncing files to device Linux...                         
flutter: I new RepositoryManager: Repo Ids [0]
Syncing files to device Linux...                         
flutter: I new RepositoryManager: Current Id 0
Syncing files to device Linux...                         
flutter: D logEvent: Event.StorageConfig
Syncing files to device Linux...                         
flutter: D logEvent: Event.FolderConfig
Syncing files to device Linux...                         
flutter: D logEvent: Event.GitConfig
Syncing files to device Linux...                         
flutter: D logEvent: Event.Settings
Syncing files to device Linux...                         
flutter: I GitJournalRepo.load: Loading Repo at path /home/taiwei.wu/Documents/journal-40397/
Syncing files to device Linux...                         
flutter: I GitJournalRepo.load: Calling GitInit for journal-40397 at: /home/taiwei.wu/Documents/journal-40397/
Syncing files to device Linux...                         
flutter: D Analytics.init: Analytics Collection: false
Syncing files to device Linux...                         
flutter: D Analytics.init: Analytics Storage: /home/taiwei.wu/.local/share/io.gitjournal.journal/analytics
Syncing files to device Linux...                         
flutter: I Analytics._sendAppUpdateEvent: App Version: 1.89.0
Syncing files to device Linux...                         
flutter: I Analytics._sendAppUpdateEvent: App Build Number: 10
Syncing files to device Linux...                         
flutter: D logEvent: Event.AppUpdate
Syncing files to device Linux...                         
flutter: D FileStorageCache.load: Loading MTimeCache: 0 items
Syncing files to device Linux...                         
flutter: D FileStorageCache.load: Loading CTimeCache: 0 items
Syncing files to device Linux...                         
flutter: I new GitJournalRepo._internal: Branch main
Syncing files to device Linux...                         
flutter: I new GitJournalRepo._internal: Cache Directory: /home/taiwei.wu/.local/share/io.gitjournal.journal/0
Syncing files to device Linux...                         
flutter: D GitJournalRepo.syncNotes: Not syncing because RemoteRepo not configured
Syncing files to device Linux...                         
flutter: D GitJournalInAppPurchases.confirmProPurchaseBoot: Ignoring IAP pro check - debug mode
Syncing files to device Linux...                         
flutter: I NotesCache.load: Notes Cache Loaded: 0 items
Syncing files to device Linux...                         
flutter: I GitJournalRepo._loadFromCache: Finished loading the notes cache - 0:00:00.023669
Syncing files to device Linux...                         
flutter: I GitJournalRepo.__fillFileStorageCache: Built Git Time Cache - 0:00:00.025765
Syncing files to device Linux...                         
flutter: D FileStorageCache.save: Saving MTimeCache: 0 items
Syncing files to device Linux...                         
flutter: D FileStorageCache.save: Saving CTimeCache: 0 items
Syncing files to device Linux...                                   353ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application
running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on Linux is available at:
http://127.0.0.1:33973/fkw3dZIQDpc=/
flutter: D logEvent: Event.AppFirstOpen
The Flutter DevTools debugger and profiler on Linux is
available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:33973/fkw3dZIQ
Dpc=/
flutter: I GitJournalRepo.__fillFileStorageCache: Built Git Time Cache - 0:00:00.005578
flutter: D FileStorageCache.save: Saving MTimeCache: 0 items
flutter: D FileStorageCache.save: Saving CTimeCache: 0 items
flutter: I GitJournalRepo._loadFromCache: Finished loading all the notes - 0:00:01.222905
flutter: ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown while notifying status listeners for AnimationController:
flutter: The Scrollbar's ScrollController has no ScrollPosition attached.
flutter: A Scrollbar cannot be painted without a ScrollPosition.
flutter: The Scrollbar attempted to use the PrimaryScrollController. This ScrollController should be
flutter: associated with the ScrollView that the Scrollbar is being applied to.
flutter: If a ScrollController has not been provided, the PrimaryScrollController is used by default on
flutter: mobile platforms for ScrollViews with an Axis.vertical scroll direction.
flutter: To use the PrimaryScrollController explicitly, set ScrollView.primary to true on the Scrollable
flutter: widget.
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1451:9)
flutter: #1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1482:6)
flutter: #2      RawScrollbarState._validateInteractions (package:flutter/src/widgets/scrollbar.dart:1420:14)
flutter: #3      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:240:19)
flutter: #4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:893:7)
flutter: #5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:824:5)
flutter: #6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:691:12)
flutter: #7      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:500:12)
flutter: #8      RawScrollbarState.handleHover (package:flutter/src/widgets/scrollbar.dart:2072:35)
flutter: #9      _MaterialScrollbarState.handleHover (package:flutter/src/material/scrollbar.dart:372:11)
flutter: #10     RawScrollbarState.build.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:2192:25)
flutter: #11     RenderMouseRegion.handleEvent (package:flutter/src/rendering/proxy_box.dart:3170:22)
flutter: #12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:481:22)
flutter: #13     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450:11)
flutter: #14     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:426:7)
flutter: #15     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:389:5)
flutter: #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:336:7)
flutter: #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:305:9)
flutter: #21     _invoke1 (dart:ui/hooks.dart:330:10)
flutter: #22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
flutter: #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
flutter: (elided 3 frames from dart:async)
flutter: 
flutter: The AnimationController notifying status listeners was:
flutter:   AnimationController#a1e49(▶ 0.000)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: The Scrollbar's ScrollController has no ScrollPosition attached.
flutter: Another exception was thrown: The Scrollbar's ScrollController has no ScrollPosition attached.
flutter: D logEvent: Event.DrawerSetupGitHost
flutter: D GitHostSetupButton._onPressedWithAnalytics: githostsetup_button_click GitHub
flutter: D logEvent: Event.GitHostSetupButtonClick
flutter: D GitHostSetupButton._onPressedWithAnalytics: githostsetup_button_click Let me do it manually
flutter: D logEvent: Event.GitHostSetupButtonClick
flutter: D GitHostSetupButton._onPressedWithAnalytics: githostsetup_button_click Open Create New Repo Webpage
flutter: D logEvent: Event.GitHostSetupButtonClick
Opening in existing browser session.
flutter: D GitHostSetupButton._onPressedWithAnalytics: githostsetup_button_click Next
flutter: D logEvent: Event.GitHostSetupButtonClick
flutter: D GitHostSetupButton._onPressedWithAnalytics: githostsetup_button_click Generate new keys
flutter: D logEvent: Event.GitHostSetupButtonClick
flutter: D GitHostSetupScreenState._generateSshKey.<ac>.<ac>: PublicKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHPi17XUEclDV28XMRfPfAhbSjQBpHG/BqdCHXO7sXZX GitJournal-linux-2024-08-19

flutter: D GitHostSetupButton._onPressedWithAnalytics: githostsetup_button_click Copy Key
flutter: D logEvent: Event.GitHostSetupButtonClick
flutter: D GitHostSetupButton._onPressedWithAnalytics: githostsetup_button_click Clone Repo
flutter: D logEvent: Event.GitHostSetupButtonClick
flutter: I GitHostSetupScreenState._startGitClone: RepoPath: /home/taiwei.wu/Documents/journal-40397
flutter: I _gitCommandViaExecutable: Running git clone git@github.com:TieWay59/notes.git /home/taiwei.wu/Documents/journal-40397
flutter: D _gitCommandViaExecutable: env GIT_SSH_COMMAND="ssh -i /tmp/NAYYOW/key -o IdentitiesOnly=yes"
flutter: D _gitCommandViaExecutable: git clone git@github.com:TieWay59/notes.git /home/taiwei.wu/Documents/journal-40397
flutter: E GitHostSetupScreenState._startGitClone: Failed to clone Exception: Failed to fetch -  - exitCode: 128package:gitjournal/utils/git_desktop.dart 96:5  _gitCommandViaExecutable
package:gitjournal/setup/clone.dart 68:12       cloneRemotePluggable
package:git_setup/screens.dart 568:7            GitHostSetupScreenState._startGitClone

flutter: D logEvent: Event.GitHostSetupGitCloneError
```

**Comment by TieWay59** [comment]
## story

Hi @vHanda, I saw you working on some bugs lately, I appreciate your work. And I used to have clone issue in the Android app, so today I tried to build&test source code.

So, this code is break in my case:

```dart
  var process = await Process.start(
    'git',
    args,
    workingDirectory: repoPath,
    environment: {
      if (privateKey.isNotEmpty)
        'GIT_SSH_COMMAND': 'ssh -i ${temp.path} -o IdentitiesOnly=yes',
    },
  );
```

I'm not an expert dart dev, so would you mind sharing some ideas on why this failed? I can help with fixing it.

**Comment by TieWay59** [comment]
@vHanda Thank you for your reply. I fully understand your schedule. Using go-git would be nice for consistent behavior in future debug & local tests.

I hit some errors when compiling the Android version, yesterday. It's not very easy to build it. I'll try to summarize the issue and open another one.

(I thought this would be related to your recent working feature, so IDK if is this fail expected.)

**Comment by vHanda** [comment]
@TieWay59 : What are the problems you're having with compiling the android app? I'd have thought now with 'go-git', it would be fairly trivial. Especially since one doesn't even need the NDK.
