### ISSUE TITLE
Not working on Android 14 / Lineageos 21 ? 

### ISSUE THREAD

**Issue by laem** [GitJournal/GitJournal#978]
Cloning a 200 ko github repo leads to an infinite 'cloning' message... Using new LineageOS 21 rom.

Tried to remove data and app and reinstall, same result. Tried gitlab, got "The authorization does not support this response type". 

Sad :/ This is a awesome app.

**Comment by laem** [comment]
OK, got a clue : installing from Fdroid lead to these cloning errors. Installing from Aurora (PlayStore) works perfectly for github host (didn't try gitlab).

**Comment by vHanda** [comment]
Could you please provide the logs? Settings -> debug logs.

**Comment by Morpheus0x** [comment]
I am experiencing the same issue on the latest f-droid version (1.89.0+3798) from the provided repo (https://github.com/GitJournal/fdroid). I am trying to use a repo from my own Forgejo server but also tried the same using the manual method for github. Both seem to hang at `Cloning...` for repos that only contain a readme file. Even the automatic github mehtod doesn't work in the f-droid version. After selecting the repository it still hangs. The debug log is all follows: 
```
{"t":1728973214631,"l":"i","msg":"--------------------------------"}
{"t":1728973214631,"l":"i","msg":"--------------------------------"}
{"t":1728973214631,"l":"i","msg":"--------------------------------"}
{"t":1728973214631,"l":"i","msg":"--------- App Launched ---------"}
{"t":1728973214631,"l":"i","msg":"--------------------------------"}
{"t":1728973214631,"l":"i","msg":"--------------------------------"}
{"t":1728973214631,"l":"i","msg":"--------------------------------"}
{"t":1728973214631,"l":"i","msg":"AppConfig","p":{"onBoardingCompleted":"true","collectCrashReports":"true","version":"0","validateProMode":"true","proMode":"false","debugLogLevel":"v","experimentalMarkdownToolbar":"false","experimentalAccounts":"false","experimentalTagAutoCompletion":"false"}}
{"t":1728973214632,"l":"i","msg":"Repo Ids [0]"}
{"t":1728973214632,"l":"i","msg":"Current Id 0"}
{"t":1728973214632,"l":"d","msg":"Event.StorageConfig","p":{"folderName":"default","storeInternally":"true","storageLocation":"","id":"0"}}
{"t":1728973214632,"l":"d","msg":"Event.FolderConfig","p":{"noteFileNameFormat":"FromTitle","journalNoteFileNameFormat":"FromTitle","yamlModifiedKey":"modified","yamlCreatedKey":"created","yamlTagsKey":"tags","yamlEditorTypeKey":"type","yamlHeaderEnabled":"true","defaultEditor":"Markdown","defaultView":"Standard","defaultFileFormat":"Markdown","sortingField":"Modified","sortingOrder":"desc","showNoteSummary":"true","folderViewHeaderType":"TitleGenerated","imageLocationSpec":".","titleSettings":"h1","inlineTagPrefixes":"#","emojify":"false","allowedFileExts":".md .txt .org","id":"0"}}
{"t":1728973214632,"l":"d","msg":"Event.GitConfig","p":{"gitAuthor":"true","gitAuthorEmail":"true","sshPublicKey":"false","sshPrivateKey":"false","sshPassword":"false","id":"0"}}
{"t":1728973214632,"l":"d","msg":"Event.Settings","p":{"customMetaData":"","defaultNewNoteFolderSpec":"false","journalEditordefaultNewNoteFolderSpec":"","journalEditorSingleNote":"false","remoteSyncFrequency":"automatic","version":"3","markdownDefaultView":"Last Used","markdownLastUsedView":"Edit","homeScreen":"all_notes","theme":"default","lightTheme":"LightDefault","darkTheme":"DarkDefault","zenMode":"false","swipeToDelete":"true","emojiParser":"true","bottomMenuBar":"true","confirmDelete":"true","id":"0"}}
{"t":1728973214632,"l":"i","msg":"Loading Repo at path /data/user/0/io.gitjournal.gitjournal/app_flutter/journal/"}
{"t":1728973214634,"l":"d","msg":"Analytics Collection: true"}
{"t":1728973214634,"l":"d","msg":"Analytics Storage: /data/user/0/io.gitjournal.gitjournal/files/analytics"}
{"t":1728973214636,"l":"d","msg":"BlobCTimeBuilder Cache Size: 0.12 Kb"}
{"t":1728973214637,"l":"d","msg":"FileMTimeBuilder Cache Size: 0.11 Kb"}
{"t":1728973214638,"l":"d","msg":"Loading MTimeCache: 1 items"}
{"t":1728973214638,"l":"d","msg":"Loading CTimeCache: 1 items"}
{"t":1728973214639,"l":"i","msg":"App Version: 1.89.0"}
{"t":1728973214639,"l":"i","msg":"App Build Number: 3798"}
{"t":1728973214640,"l":"i","msg":"Branch main"}
{"t":1728973214640,"l":"i","msg":"Cache Directory: /data/user/0/io.gitjournal.gitjournal/files/0"}
{"t":1728973214640,"l":"d","msg":"Not syncing because RemoteRepo not configured"}
{"t":1728973214640,"l":"i","msg":"Trying to confirmProPurchase"}
{"t":1728973214666,"l":"i","msg":"Built Git Time Cache - 0:00:00.026170"}
{"t":1728973214666,"l":"d","msg":"Saving MTimeCache: 1 items"}
{"t":1728973214666,"l":"d","msg":"Saving CTimeCache: 1 items"}
{"t":1728973214669,"l":"d","msg":"Received MediaFile Share with App (media): []"}
{"t":1728973214670,"l":"i","msg":"Notes Cache Loaded: 1 items"}
{"t":1728973214670,"l":"i","msg":"Finished loading the notes cache - 0:00:00.029927"}
{"t":1728973214677,"l":"d","msg":"Saving MTimeCache: 1 items"}
{"t":1728973214677,"l":"d","msg":"Saving CTimeCache: 1 items"}
{"t":1728973214679,"l":"d","msg":"Note modified: Test Note.md"}
{"t":1728973214684,"l":"i","msg":"Finished loading all the notes - 0:00:00.014629"}
{"t":1728973214696,"l":"i","msg":"Sending 16 events"}
{"t":1728973214699,"l":"i","msg":"Loading View 0_summary_v2: 0:00:00.003860"}
{"t":1728973215111,"l":"d","msg":"[https://analytics-wetu2tkdpq-ew.a.run.app/v1/sendData] An error occurred during request, trying again (attempt: 1/3, wait 1000 ms, error: Http status error [500])"}
{"t":1728973216248,"l":"d","msg":"[https://analytics-wetu2tkdpq-ew.a.run.app/v1/sendData] An error occurred during request, trying again (attempt: 2/3, wait 5000 ms, error: Http status error [500])"}
{"t":1728973218280,"l":"d","msg":"Event.DrawerSetupGitHost"}
{"t":1728973220495,"l":"d","msg":"githostsetup_button_click Custom"}
{"t":1728973220497,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Custom","icon_url":""}}
{"t":1728973221506,"l":"d","msg":"[https://analytics-wetu2tkdpq-ew.a.run.app/v1/sendData] An error occurred during request, trying again (attempt: 3/3, wait 15000 ms, error: Http status error [500])"}
{"t":1728973236753,"l":"e","msg":"Failed to send Analytics","ex":"DioError [DioErrorType.response]: Http status error [500] Source stack: #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488) #1      DioMixin.request (package:dio/src/dio_mixin.dart:483) #2      DioMixin.post (package:dio/src/dio_mixin.dart:97) #3      sendAnalytics (package:gitjournal/analytics/network.dart:36) #4      Analytics._sendAnalytics.<anonymous closure> (package:gitjournal/analytics/analytics.dart:159) <asynchronous suspension> #5      AnalyticsStorage.fetchAll.<anonymous closure> (package:gitjournal/analytics/storage.dart:129) <asynchronous suspension> #6      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33) <asynchronous suspension> #7      AnalyticsStorage.fetchAll (package:gitjournal/analytics/storage.dart:119) <asynchronous suspension> #8      Analytics._sendAnalytics (package:gitjournal/analytics/analytics.dart:150) <asynchronous suspension> #9      Analytics.log (package:gitjournal/analytics/analytics.dart:118) <asynchronous suspension> #10     AnalyticsRouteObserver._sendScreenView (package:gitjournal/analytics/route_observer.dart:25) <asynchronous suspension> ","stack":[{"uri":"package:dio/src/dio_mixin.dart","line":643,"member":"DioMixin.fetch.<fn>","isCore":false,"library":"package:dio/src/dio_mixin.dart","location":"package:dio/src/dio_mixin.dart 643","package":"dio"}]}
{"t":1728973327528,"l":"d","msg":"githostsetup_button_click Next"}
{"t":1728973327530,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Next","icon_url":""}}
{"t":1728973331698,"l":"d","msg":"githostsetup_button_click Generate new keys"}
{"t":1728973331699,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Generate new keys","icon_url":""}}
{"t":1728973331706,"l":"d","msg":"PublicKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM4/xlm97klW5jb6qlnJbmdidZKhUSaIcd1fsDHq6jKA GitJournal-android-2024-10-15 "}
{"t":1728973471271,"l":"d","msg":"githostsetup_button_click Clone Repo"}
{"t":1728973471274,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Clone Repo","icon_url":""}}
{"t":1728973471275,"l":"i","msg":"RepoPath: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal"}
{"t":1728973525182,"l":"d","msg":"githostsetup_button_click Next"}
{"t":1728973525185,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Next","icon_url":""}}
{"t":1728973531254,"l":"d","msg":"githostsetup_button_click Generate new keys"}
{"t":1728973531257,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Generate new keys","icon_url":""}}
{"t":1728973535852,"l":"d","msg":"githostsetup_button_click Copy Key"}
{"t":1728973535854,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Copy Key","icon_url":""}}
{"t":1728973536792,"l":"d","msg":"githostsetup_button_click Clone Repo"}
{"t":1728973536794,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Clone Repo","icon_url":""}}
{"t":1728973536794,"l":"i","msg":"RepoPath: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal"}
{"t":1728974057127,"l":"d","msg":"githostsetup_button_click Next"}
{"t":1728974057131,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Next","icon_url":""}}
{"t":1728974057999,"l":"d","msg":"githostsetup_button_click Generate new keys"}
{"t":1728974058000,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Generate new keys","icon_url":""}}
{"t":1728974059205,"l":"d","msg":"githostsetup_button_click Copy Key"}
{"t":1728974059206,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Copy Key","icon_url":""}}
{"t":1728974099470,"l":"d","msg":"githostsetup_button_click Clone Repo"}
{"t":1728974099474,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Clone Repo","icon_url":""}}
{"t":1728974099474,"l":"i","msg":"RepoPath: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal"}
{"t":1728974228396,"l":"d","msg":"githostsetup_button_click Clone Repo"}
{"t":1728974228397,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Clone Repo","icon_url":""}}
{"t":1728974228397,"l":"i","msg":"RepoPath: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal"}
{"t":1728974291661,"l":"e","msg":"createBugReport","ex":"PlatformException(not_available, No email clients found!, null, null)","stack":[{"uri":"package:flutter/src/services/message_codecs.dart","line":648,"member":"StandardMethodCodec.decodeEnvelope","isCore":false,"library":"package:flutter/src/services/message_codecs.dart","location":"package:flutter/src/services/message_codecs.dart 648","package":"flutter"},{"uri":"package:flutter/src/services/platform_channel.dart","line":334,"member":"MethodChannel._invokeMethod","isCore":false,"library":"package:flutter/src/services/platform_channel.dart","location":"package:flutter/src/services/platform_channel.dart 334","package":"flutter"},{"uri":"package:gitjournal/settings/bug_report.dart","line":33,"member":"createBugReport","isCore":false,"library":"package:gitjournal/settings/bug_report.dart","location":"package:gitjournal/settings/bug_report.dart 33","package":"gitjournal"},{"uri":"package:gitjournal/widgets/app_drawer.dart","line":239,"member":"_AppDrawerState.build.<fn>","isCore":false,"library":"package:gitjournal/widgets/app_drawer.dart","location":"package:gitjournal/widgets/app_drawer.dart 239","package":"gitjournal"}]}
{"t":1728974291664,"l":"d","msg":"Event.DrawerBugReport"}
{"t":1728974295641,"l":"d","msg":"Event.DrawerSettings"}
{"t":1728974298789,"l":"e","msg":"createBugReport","ex":"PlatformException(not_available, No email clients found!, null, null)","stack":[{"uri":"package:flutter/src/services/message_codecs.dart","line":648,"member":"StandardMethodCodec.decodeEnvelope","isCore":false,"library":"package:flutter/src/services/message_codecs.dart","location":"package:flutter/src/services/message_codecs.dart 648","package":"flutter"},{"uri":"package:flutter/src/services/platform_channel.dart","line":334,"member":"MethodChannel._invokeMethod","isCore":false,"library":"package:flutter/src/services/platform_channel.dart","location":"package:flutter/src/services/platform_channel.dart 334","package":"flutter"},{"uri":"package:gitjournal/settings/bug_report.dart","line":33,"member":"createBugReport","isCore":false,"library":"package:gitjournal/settings/bug_report.dart","location":"package:gitjournal/settings/bug_report.dart 33","package":"gitjournal"}]}
{"t":1728974298793,"l":"d","msg":"Event.DrawerBugReport"}
{"t":1728974384547,"l":"i","msg":"--------------------------------"}
{"t":1728974384547,"l":"i","msg":"--------------------------------"}
{"t":1728974384547,"l":"i","msg":"--------------------------------"}
{"t":1728974384547,"l":"i","msg":"--------- App Launched ---------"}
{"t":1728974384547,"l":"i","msg":"--------------------------------"}
{"t":1728974384547,"l":"i","msg":"--------------------------------"}
{"t":1728974384547,"l":"i","msg":"--------------------------------"}
{"t":1728974384547,"l":"i","msg":"AppConfig","p":{"onBoardingCompleted":"true","collectCrashReports":"true","version":"0","validateProMode":"true","proMode":"false","debugLogLevel":"v","experimentalMarkdownToolbar":"false","experimentalAccounts":"false","experimentalTagAutoCompletion":"false"}}
{"t":1728974384548,"l":"d","msg":"Analytics Collection: true"}
{"t":1728974384548,"l":"d","msg":"Analytics Storage: /data/user/0/io.gitjournal.gitjournal/files/analytics"}
{"t":1728974384548,"l":"i","msg":"Repo Ids [0]"}
{"t":1728974384548,"l":"i","msg":"Current Id 0"}
{"t":1728974384548,"l":"d","msg":"Event.StorageConfig","p":{"folderName":"default","storeInternally":"true","storageLocation":"","id":"0"}}
{"t":1728974384549,"l":"d","msg":"Event.FolderConfig","p":{"noteFileNameFormat":"FromTitle","journalNoteFileNameFormat":"FromTitle","yamlModifiedKey":"modified","yamlCreatedKey":"created","yamlTagsKey":"tags","yamlEditorTypeKey":"type","yamlHeaderEnabled":"true","defaultEditor":"Markdown","defaultView":"Standard","defaultFileFormat":"Markdown","sortingField":"Modified","sortingOrder":"desc","showNoteSummary":"true","folderViewHeaderType":"TitleGenerated","imageLocationSpec":".","titleSettings":"h1","inlineTagPrefixes":"#","emojify":"false","allowedFileExts":".md .txt .org","id":"0"}}
{"t":1728974384549,"l":"d","msg":"Event.GitConfig","p":{"gitAuthor":"true","gitAuthorEmail":"true","sshPublicKey":"true","sshPrivateKey":"true","sshPassword":"false","id":"0"}}
{"t":1728974384549,"l":"d","msg":"Event.Settings","p":{"customMetaData":"","defaultNewNoteFolderSpec":"false","journalEditordefaultNewNoteFolderSpec":"","journalEditorSingleNote":"false","remoteSyncFrequency":"automatic","version":"3","markdownDefaultView":"Last Used","markdownLastUsedView":"Edit","homeScreen":"all_notes","theme":"default","lightTheme":"LightDefault","darkTheme":"DarkDefault","zenMode":"false","swipeToDelete":"true","emojiParser":"true","bottomMenuBar":"true","confirmDelete":"true","id":"0"}}
{"t":1728974384549,"l":"i","msg":"Loading Repo at path /data/user/0/io.gitjournal.gitjournal/app_flutter/journal/"}
{"t":1728974384550,"l":"i","msg":"App Version: 1.89.0"}
{"t":1728974384550,"l":"i","msg":"App Build Number: 3798"}
{"t":1728974384552,"l":"d","msg":"BlobCTimeBuilder Cache Size: 0.12 Kb"}
{"t":1728974384552,"l":"d","msg":"FileMTimeBuilder Cache Size: 0.11 Kb"}
{"t":1728974384553,"l":"d","msg":"Loading MTimeCache: 1 items"}
{"t":1728974384553,"l":"d","msg":"Loading CTimeCache: 1 items"}
{"t":1728974384553,"l":"i","msg":"Branch main"}
{"t":1728974384553,"l":"i","msg":"Cache Directory: /data/user/0/io.gitjournal.gitjournal/files/0"}
{"t":1728974384553,"l":"d","msg":"Not syncing because RemoteRepo not configured"}
{"t":1728974384553,"l":"i","msg":"Trying to confirmProPurchase"}
{"t":1728974384572,"l":"d","msg":"Received MediaFile Share with App (media): []"}
{"t":1728974384604,"l":"i","msg":"Built Git Time Cache - 0:00:00.049915"}
{"t":1728974384604,"l":"d","msg":"Saving MTimeCache: 1 items"}
{"t":1728974384604,"l":"d","msg":"Saving CTimeCache: 1 items"}
{"t":1728974384605,"l":"i","msg":"Notes Cache Loaded: 1 items"}
{"t":1728974384605,"l":"i","msg":"Finished loading the notes cache - 0:00:00.051875"}
{"t":1728974384612,"l":"d","msg":"Saving MTimeCache: 1 items"}
{"t":1728974384612,"l":"d","msg":"Saving CTimeCache: 1 items"}
{"t":1728974384613,"l":"d","msg":"Note modified: Test Note.md"}
{"t":1728974384616,"l":"i","msg":"Finished loading all the notes - 0:00:00.011138"}
{"t":1728974384630,"l":"i","msg":"Loading View 0_summary_v2: 0:00:00.003877"}
{"t":1728974387804,"l":"d","msg":"Event.DrawerSetupGitHost"}
{"t":1728974388971,"l":"d","msg":"githostsetup_button_click Custom"}
{"t":1728974388972,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Custom","icon_url":""}}
{"t":1728974396553,"l":"d","msg":"githostsetup_button_click GitHub"}
{"t":1728974396554,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"GitHub","icon_url":"assets/icon/github-icon.png"}}
{"t":1728974398358,"l":"d","msg":"githostsetup_button_click Let me do it manually"}
{"t":1728974398360,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Let me do it manually","icon_url":""}}
{"t":1728974402674,"l":"d","msg":"githostsetup_button_click Setup Automatically"}
{"t":1728974402675,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Setup Automatically","icon_url":""}}
{"t":1728974405741,"l":"d","msg":"githostsetup_button_click GitLab"}
{"t":1728974405742,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"GitLab","icon_url":"assets/icon/gitlab-icon.png"}}
{"t":1728974406875,"l":"d","msg":"githostsetup_button_click Setup Automatically"}
{"t":1728974406877,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Setup Automatically","icon_url":""}}
{"t":1728974412536,"l":"d","msg":"githostsetup_button_click Custom"}
{"t":1728974412538,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Custom","icon_url":""}}
{"t":1728974594486,"l":"d","msg":"githostsetup_button_click Next"}
{"t":1728974594489,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Next","icon_url":""}}
{"t":1728974597864,"l":"d","msg":"githostsetup_button_click Generate new keys"}
{"t":1728974597867,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Generate new keys","icon_url":""}}
{"t":1728974597890,"l":"d","msg":"PublicKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOKVgLPI8Ka0/YpI1Mxn69F16iG1YZe/v24WB/nAwFfL GitJournal-android-2024-10-15 "}
{"t":1728974601811,"l":"d","msg":"githostsetup_button_click Copy Key"}
{"t":1728974601813,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Copy Key","icon_url":""}}
{"t":1728974723952,"l":"d","msg":"githostsetup_button_click Clone Repo"}
{"t":1728974723956,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Clone Repo","icon_url":""}}
{"t":1728974723957,"l":"i","msg":"RepoPath: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal"}
{"t":1728974883307,"l":"d","msg":"Event.DrawerSettings"}
{"t":1728975064892,"l":"d","msg":"Event.DrawerSetupGitHost"}
{"t":1728975065731,"l":"d","msg":"githostsetup_button_click GitHub"}
{"t":1728975065732,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"GitHub","icon_url":"assets/icon/github-icon.png"}}
{"t":1728975066946,"l":"d","msg":"githostsetup_button_click Let me do it manually"}
{"t":1728975066948,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Let me do it manually","icon_url":""}}
{"t":1728975137572,"l":"d","msg":"Event.DrawerSettings"}
{"t":1728975227302,"l":"d","msg":"Event.DrawerSetupGitHost"}
{"t":1728975228122,"l":"d","msg":"githostsetup_button_click GitHub"}
{"t":1728975228125,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"GitHub","icon_url":"assets/icon/github-icon.png"}}
{"t":1728975229408,"l":"d","msg":"githostsetup_button_click Setup Automatically"}
{"t":1728975229409,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Setup Automatically","icon_url":""}}
{"t":1728975230163,"l":"d","msg":"githostsetup_button_click Authorize GitJournal"}
{"t":1728975230163,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Authorize GitJournal","icon_url":""}}
{"t":1728975230163,"l":"d","msg":"Starting autoconfigure"}
{"t":1728975230163,"l":"d","msg":"GitHub: Installed Handler"}
{"t":1728975261223,"l":"d","msg":"GitHub: Called onUrl with {URL: gitjournal://login.oauth2?code=c347176186a934ccb478}"}
{"t":1728975261546,"l":"d","msg":"GitHost Initalized: GitHostType.GitHub"}
{"t":1728975261546,"l":"d","msg":"Starting to fetch userInfo"}
{"t":1728975261862,"l":"d","msg":"Got UserInfo - UserInfo{name: false, email: false, username: true}"}
{"t":1728975261871,"l":"i","msg":"Got User Info: UserInfo{name: false, email: false, username: true}"}
{"t":1728975261875,"l":"d","msg":"Starting RepoSelector"}
{"t":1728975261891,"l":"d","msg":"Starting RepoSelector"}
{"t":1728975266640,"l":"d","msg":"githostsetup_button_click Next"}
{"t":1728975266641,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Next","icon_url":""}}
{"t":1728975266641,"l":"d","msg":"Starting autoconfigure copletion"}
{"t":1728975266641,"l":"i","msg":"Generating SSH Key"}
{"t":1728975266673,"l":"i","msg":"Adding as a deploy key"}
{"t":1728975267656,"l":"d","msg":"GitHub addDeployKey: {\"id\":110184826,\"key\":\"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDFxwFdQcGQou73DPsk95VZr/6yOMJgjSqMLBbODUfJs\",\"url\":\"https://api.github.com/repos/Morpheus0x/DemoNotes/keys/110184826\",\"title\":\"GitJournal\",\"verified\":true,\"created_at\":\"2024-10-15T06:54:26Z\",\"read_only\":false,\"last_used\":null,\"added_by\":\"Morpheus0x\"}"}
{"t":1728975267658,"l":"i","msg":"RepoPath: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal"}
{"t":1728975350739,"l":"d","msg":"Starting RepoSelector"}
{"t":1728975355981,"l":"d","msg":"Event.DrawerSettings"}
```
